import {createApi,safeUrl} from './api.js';
const content=document.querySelector('#content'),notice=document.querySelector('#notice'),logout=document.querySelector('#logout');
let signedIn=false,view=0,urls=[];
const api=createApi(fetch,()=>{signedIn=false;auth();});
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function message(text=''){notice.textContent=text;}
function reset(title,subtitle){view++;urls.forEach(URL.revokeObjectURL);urls=[];content.replaceChildren(el('h1',title),el('p',subtitle));message();logout.hidden=!signedIn;return view;}
function button(text,action,cls){const b=el('button',text,cls);b.type='button';b.onclick=()=>run(b,action);return b;}
async function run(b,action){b.disabled=true;message();try{await action();}catch(e){content.querySelectorAll('.loading').forEach(n=>n.remove());message(e.message+(e.code?' ('+e.code+')':''));}finally{b.disabled=false;}}
function field(form,label,name,type='text',max){const l=el('label',label),n=el(type==='textarea'?'textarea':'input');n.name=name;if(type!=='textarea')n.type=type;if(max)n.maxLength=max;l.append(n);form.append(l);return n;}
function pager(page,total,load){const row=el('div',undefined,'row');const prev=button('이전',()=>load(page-1)),next=button('다음',()=>load(page+1));prev.disabled=page===0;next.disabled=page+1>=total;row.append(prev,el('span',`${page+1} / ${Math.max(1,total)}`),next);content.append(row);}
function auth(signup=false){reset(signup?'작품 보호를 시작하세요':'다시 만나 반갑습니다','로컬 개발용 화면입니다. 새로고침하면 다시 로그인합니다.');const form=el('form',undefined,'panel auth');const email=field(form,'이메일','email','email',254);email.required=true;email.autocomplete='username';const password=field(form,'비밀번호','password','password',72);password.required=true;password.autocomplete=signup?'new-password':'current-password';if(signup)password.minLength=12;const nickname=signup?field(form,'닉네임','nickname','text',50):null;if(nickname)nickname.required=true;
 const submit=el('button',signup?'가입하기':'로그인','primary');submit.type='submit';form.append(submit,button(signup?'로그인으로 돌아가기':'새 계정 만들기',()=>auth(!signup)));form.onsubmit=e=>{e.preventDefault();run(submit,async()=>{if(new TextEncoder().encode(password.value).length>72)throw Error('비밀번호는 UTF-8 기준 72바이트 이하여야 합니다.');const body={email:email.value,password:password.value};if(signup){await api.request('/auth/signup',{method:'POST',body:{...body,nickname:nickname.value}});auth();message('가입했습니다. 로그인해 주세요.');}else{await api.login(body);signedIn=true;await artworks();}});};content.append(form);}
async function artworks(page=0){if(!signedIn)return auth();const stamp=reset('내 작품','작품을 등록하고 분석 진행 상태를 확인하세요.');content.append(button('작품 등록',upload,'primary'));const loading=el('p','작품을 불러오는 중…','loading');content.append(loading);const data=await api.request(`/artworks?page=${page}&size=12`);if(stamp!==view)return;loading.remove();const grid=el('div',undefined,'grid');for(const a of data.items){const card=el('article',undefined,'card');card.append(el('span',a.monitoringEnabled?'모니터링 켜짐':'모니터링 꺼짐','badge'),el('h2',a.title),el('p',`${a.width} × ${a.height}`));card.append(button('작품 및 작업 상태',()=>artwork(a.id)),button('탐지 결과',()=>detections(0,a.id)));grid.append(card);}content.append(grid);if(!data.items.length)content.append(el('div','아직 등록한 작품이 없습니다. 첫 작품을 업로드하세요.','panel'));pager(page,data.totalPages,artworks);}
function upload(){reset('새 작품 등록','PNG 또는 JPEG · 최대 20 MiB');const form=el('form',undefined,'panel');const title=field(form,'작품 제목','title','text',200);title.required=true;const description=field(form,'설명','description','textarea',5000);const file=field(form,'이미지','file','file');file.accept='image/png,image/jpeg';file.required=true;const submit=el('button','업로드하고 등록','primary');submit.type='submit';form.append(submit);form.onsubmit=e=>{e.preventDefault();run(submit,async()=>{const f=file.files[0];if(!f||!['image/png','image/jpeg'].includes(f.type)||f.size<1||f.size>20971520)throw Error('20 MiB 이하 PNG/JPEG 파일을 선택해 주세요.');const stamp=view;message('업로드 준비 중…');const u=await api.request('/artworks/upload-url',{method:'POST',body:{contentType:f.type,sizeBytes:f.size}});const url=safeUrl(u.uploadUrl);if(!url)throw Error('업로드 주소를 확인할 수 없습니다.');const r=await fetch(url,{method:'PUT',headers:u.requiredHeaders,body:f,credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)throw Error('이미지 업로드가 실패했습니다. 저장소 연결과 CORS 설정을 확인해 주세요.');const a=await api.request('/artworks',{method:'POST',body:{uploadId:u.uploadId,title:title.value,description:description.value}});if(stamp===view)await artwork(a.id);});};content.append(form);}
async function artwork(id){const stamp=reset('작품 상세','분석 요청 후 상태 확인 버튼으로 진행 상황을 갱신할 수 있습니다.');const a=await api.request('/artworks/'+id);if(stamp!==view)return;const card=el('div',undefined,'panel');card.append(el('h2',a.title),el('p',a.description));content.append(card);const image=el('img',undefined,'preview');image.alt=a.title;image.onerror=()=>image.replaceWith(el('p','이미지를 불러오지 못했습니다.'));card.append(image);api.request(`/artworks/${id}/image-url`).then(data=>{if(stamp===view&&safeUrl(data.url))image.src=safeUrl(data.url);}).catch(()=>{image.replaceWith(el('p','이미지를 불러오지 못했습니다.'));});
 const state=el('p','임베딩 상태를 확인하세요.');card.append(state);const show=j=>{if(stamp!==view)return;state.textContent=`작업 상태: ${j.status}${j.errorCode?' · '+j.errorCode:''}`;};card.append(button('임베딩 상태 확인',async()=>show(await api.request(`/artworks/${id}/embedding`))),button('임베딩 요청 / 재시도',async()=>show(await api.request(`/artworks/${id}/embedding`,{method:'POST'}))));
 const jobPanel=el('div',undefined,'panel');jobPanel.append(el('h2','유사 상품 탐지'));card.append(button('탐지 요청',async()=>{const j=await api.request(`/artworks/${id}/detections`,{method:'POST'});if(stamp!==view)return;jobPanel.replaceChildren(el('h2','유사 상품 탐지'));const status=el('p',`작업 상태: ${j.status}`);jobPanel.append(status,button('탐지 상태 확인',async()=>{const latest=await api.request(`/artworks/${id}/detection-jobs/${j.jobId}`);status.textContent=`작업 상태: ${latest.status}${latest.errorCode?' · '+latest.errorCode:''}`;}),button('실패한 탐지 재시도',async()=>{const latest=await api.request(`/artworks/${id}/detection-jobs/${j.jobId}/retry`,{method:'POST'});status.textContent='작업 상태: '+latest.status;}));}));jobPanel.append(el('p','탐지 요청을 시작하면 작업 상태 확인 기능이 나타납니다.'));content.append(jobPanel,button('탐지 결과 보기',()=>detections(0,id)));}
async function detections(page=0,artworkId='',status='',severity=''){if(!signedIn)return auth();const stamp=reset('탐지 검토','이미지 유사도에 따른 검토 대상입니다. 저작권 침해 여부를 확정하지 않습니다.');const filters=el('div',undefined,'row');function select(label,options,value){const l=el('label',label),s=el('select');for(const [v,t]of options){const o=el('option',t);o.value=v;s.append(o);}s.value=value;l.append(s);filters.append(l);return s;}const st=select('검토 상태',[['','전체'],['NEW','미검토'],['CONFIRMED','확인'],['DISMISSED','제외']],status),sv=select('심각도',[['','전체'],['MEDIUM','MEDIUM'],['HIGH','HIGH'],['CRITICAL','CRITICAL']],severity);filters.append(button('필터 적용',()=>detections(0,artworkId,st.value,sv.value)));content.append(filters);const loading=el('p','탐지 결과를 불러오는 중…','loading');content.append(loading);const q=new URLSearchParams({page,size:12,...(artworkId?{artworkId}:{}),...(status?{status}:{}),...(severity?{severity}:{})});const data=await api.request('/detections?'+q);if(stamp!==view)return;loading.remove();const grid=el('div',undefined,'grid');for(const d of data.items){const card=el('article',undefined,'card');card.append(el('span',d.severity+' · '+d.status,'badge'),el('h2',d.productTitle),el('p',d.artworkTitle),el('p',`유사도 ${(d.similarity*100).toFixed(1)}%`),button('상세 검토',()=>detail(d.id)));if(d.synthetic)card.append(el('p','합성/테스트 데이터','muted'));grid.append(card);}content.append(grid);if(!data.items.length)content.append(el('div','조건에 맞는 탐지 결과가 없습니다.','panel'));pager(page,data.totalPages,p=>detections(p,artworkId,status,severity));}
async function detail(id){const stamp=reset('탐지 상세','점수와 원본 상품을 확인한 뒤 검토 상태를 기록하세요.');const data=await api.request('/detections/'+id);if(stamp!==view)return;const d=data.detection,card=el('article',undefined,'panel');card.append(el('span',d.severity+' · '+d.status,'badge'),el('h2',d.productTitle),el('p',`등록 작품: ${d.artworkTitle}`),el('h2',`유사도 ${(d.similarity*100).toFixed(1)}%`));const original=el('img',undefined,'preview');original.alt='등록 작품: '+d.artworkTitle;original.onerror=()=>original.replaceWith(el('p','작품 이미지를 불러오지 못했습니다.'));card.append(original);api.request('/artworks/'+d.artworkId+'/image-url').then(r=>{if(stamp===view&&safeUrl(r.url))original.src=safeUrl(r.url);}).catch(()=>original.replaceWith(el('p','작품 이미지를 불러오지 못했습니다.')));const link=safeUrl(d.productUrl);if(link){const a=el('a','상품 페이지 열기');a.href=link;a.target='_blank';a.rel='noopener noreferrer';card.append(a);}if(d.synthetic)card.append(el('p','합성/테스트 데이터입니다.'));const image=el('img',undefined,'preview');image.alt='비교 상품 이미지';card.append(image);api.request(`/products/${d.productId}/images/${data.imageId}/preview`,{blob:true}).then(b=>{if(stamp!==view)return;const url=URL.createObjectURL(b);urls.push(url);image.src=url;}).catch(()=>image.replaceWith(el('p','상품 이미지를 불러오지 못했습니다.')));const row=el('div',undefined,'row');for(const [status,label]of [['NEW','미검토'],['CONFIRMED','확인'],['DISMISSED','제외']])row.append(button(label,async()=>{await api.request(`/detections/${id}/status`,{method:'PATCH',body:{status,version:d.version}});if(stamp===view)await detail(id);}));card.append(row,button('최신 상태 새로고침',()=>detail(id)));content.append(card);}
document.querySelector('#artworksNav').onclick=e=>run(e.target,()=>artworks());document.querySelector('#detectionsNav').onclick=e=>run(e.target,()=>detections());logout.onclick=e=>run(e.target,async()=>{try{await api.logout();}finally{signedIn=false;auth();}});auth();
